"use client"

import Head from "next/head";
import Banner from "@/components/Banner";
import Companies from "@/components/Companies";
import Slides from "@/components/Slides";
import OurValue from "@/components/OurValue";
import ContactUs from "@/components/ContactUs";
import GetStarted from "@/components/GetStarted";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>House</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden">
        <Banner />
        <Companies />
        <div className="px-6 sm:px-20 md:px-12 2xl:px-80">
          <div className="flex flex-col gap-2 font-bold">
            <h2 className="text-lg text-orange-400">Best Choices</h2>
            <h3 className="text-xl text-blue-600"> Popular Residencies </h3>
          </div>
          <Slides />
        </div>
        <OurValue />
        <ContactUs />
        <GetStarted />
        <Footer />
      </main>
    </>
  );
}
